"""Tests for the brief's `What already exists` inventory.

The inventory is what a session reads to answer "does something already cover
this?" before writing a new artifact. It has failed that job twice: once by
collapsing a living folder so `companies.md` showed up as "9 files", and once by
growing a row per run until it was too long to scan. Both behaviours are pinned
here — the collapse must fire on repeated series and must never fire on a living
artifact.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import scripts.build_brief as bb  # noqa: E402
from scripts.build_brief import _series_rows  # noqa: E402
from scripts.idea import DATED_PART  # noqa: E402


@pytest.fixture(autouse=True)
def _repo_at_tmp(tmp_path, monkeypatch):
    """Uncollapsed rows render paths relative to the repo root; point it at the
    fixture tree so these tests never depend on real files."""
    monkeypatch.setattr(bb, "REPO", tmp_path)


def _write(d: Path, name: str, body: str = "# Title\n") -> Path:
    p = d / name
    p.write_text(body, encoding="utf-8")
    return p


def test_dated_series_collapses_to_one_row_with_latest_date(tmp_path):
    files = [_write(tmp_path, "target-list-audit-2026-08-0%d.md" % n) for n in (6, 7, 8, 9)]
    rows = _series_rows(Path("outreach"), files)
    assert len(rows) == 1
    path, purpose = rows[0]
    assert path == "outreach/target-list-audit-*.md"
    assert "4 dated snapshots" in purpose and "2026-08-09" in purpose


def test_generated_series_collapses_and_says_not_to_edit(tmp_path):
    banner = "<!-- GENERATED by scripts/build_control_room.py -->\n# Outreach results\n"
    files = [_write(tmp_path, "results-%s.md" % a, banner) for a in ("H1", "H1A2", "H2A2")]
    rows = _series_rows(Path("outreach"), files)
    assert len(rows) == 1
    assert rows[0][0] == "outreach/results-*.md"
    assert "3 generated files" in rows[0][1]


def test_living_artifacts_are_never_collapsed(tmp_path):
    """The failure this whole section exists to prevent: a hand-maintained file
    hidden behind a count. contacts.md and companies.md must each keep a row."""
    files = [
        _write(tmp_path, "contacts.md", "---\npurpose: Every contact.\n---\n"),
        _write(tmp_path, "companies.md", "---\npurpose: The company registry.\n---\n"),
        _write(tmp_path, "research-map.md", "---\npurpose: Per-paper behaviour.\n---\n"),
    ]
    rows = _series_rows(Path("outreach"), files)
    assert len(rows) == 3
    assert [p for p, _ in rows] == [f.name for f in files]
    assert rows[0][1] == "Every contact."


def test_a_lone_dated_file_keeps_its_own_row(tmp_path):
    """One snapshot is an artifact, not a series — collapsing it would hide it
    behind a count that says less than its filename already does."""
    files = [_write(tmp_path, "2026-08-08-extraction.md", "# Assumption extraction\n")]
    rows = _series_rows(Path("02-assumptions"), files)
    assert len(rows) == 1
    assert rows[0][0].endswith("2026-08-08-extraction.md")
    assert rows[0][1] == "Assumption extraction"


def test_unrelated_dated_series_do_not_merge(tmp_path):
    files = [
        _write(tmp_path, "target-list-audit-2026-08-06.md"),
        _write(tmp_path, "target-list-audit-2026-08-07.md"),
        _write(tmp_path, "recon-dump-2026-08-06.md"),
        _write(tmp_path, "recon-dump-2026-08-07.md"),
    ]
    rows = _series_rows(Path("outreach"), files)
    assert sorted(p for p, _ in rows) == [
        "outreach/recon-dump-*.md", "outreach/target-list-audit-*.md"]


def test_dated_part_matches_folders_and_filenames():
    """Shared by the brief (what to collapse) and the validator (what must declare
    a purpose); they must agree or one will demand a purpose line the other hides."""
    for dated in ("A5-2026-08-06/interviews", "methods/2026-07-27/", "audit-2026-08-09.md"):
        assert DATED_PART.search(dated), dated
    for living in ("outreach/contacts.md", "02-assumptions/graph.md", "outreach/copy/H2A2-linkedin.md"):
        assert not DATED_PART.search(living), living
