#!/usr/bin/env python3
"""Generate methods/index.md from card frontmatter × shotgun-routing.yaml.

WHY THIS EXISTS
---------------
The index used to restate every card's name, category, family, role and
exclusion reason by hand — 58 rows, all of them second copies of facts the
cards and the routing file already owned. It also *warned* that moving a card
could silently orphan a routing family, which is a warning, not a guard.

Now the cards own their own facts (`name`, `category`, `excluded_because`) and
this script joins them with the routing file. `validate_repo.py` checks that
every routing path resolves, so an orphaned family is an error rather than a
missing lens nobody notices.

Usage:
    python3 scripts/build_methods_index.py
    python3 scripts/build_methods_index.py --check    # exit 1 if stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
METHODS = ROOT / "methods"
ROUTING = METHODS / "shotgun-routing.yaml"
INDEX = METHODS / "index.md"

FOLDER_NOTES = {
    "validation": ("Validation Methods",
                   "Not in the shotgun pool: these answer downstream validation questions rather "
                   "than interpreting the shared belief/hunch pair."),
    "mutation": ("Mutation Methods",
                 "Not in the shotgun pool: each needs interview evidence that changed the picture. "
                 "The shotgun's reframe mode consumes their conclusions through the evidence delta."),
    "intake": ("Intake",
               "Elicitation methods. Their input is the founder's memory, surfaced by asking "
               "questions — which is why no research agent can run them. Run once by "
               "`startup-belief-intake`, before a canonical belief and active hunch exist."),
    "practices": ("Practices",
                  "Methods the founder executes **in the world**, not at a desk: real traffic, a "
                  "real buyer on a real call, or months of accumulated noticing."),
    "unused": ("Unused",
               "Parked cards. Kept for reference and possible revival, never selectable by any "
               "skill. Moving a card here is a deliberate decision to take it out of rotation."),
}


def frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    try:
        data = yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError as e:
        print(f"[warn] {path.relative_to(ROOT)} frontmatter: {e}", file=sys.stderr)
        return {}
    return data if isinstance(data, dict) else {}


def routing_roles() -> dict[str, tuple[str, str]]:
    """card path → (family, role), read from shotgun-routing.yaml."""
    data = yaml.safe_load(ROUTING.read_text(encoding="utf-8")) or {}
    out: dict[str, tuple[str, str]] = {}
    pre = (data.get("pre_lens") or {}).get("method")
    if pre:
        out[pre] = ("pre_lens", "orchestration")
    for name, fam in (data.get("lens_families") or {}).items():
        if not isinstance(fam, dict):
            continue
        for role_key, label in (("primary", "primary"),
                                ("alternative", "alternative"),
                                ("alternatives", "alternative")):
            val = fam.get(role_key)
            entries = [val] if isinstance(val, str) else (val or [])
            for entry in entries:
                # alternatives are {method, when} maps; primaries are plain paths
                method = entry.get("method") if isinstance(entry, dict) else entry
                if isinstance(method, str):
                    out[method] = (name, label)
    return out


def rows_for(folder: str) -> list[tuple]:
    cards = sorted((METHODS / folder).glob("*.md"))
    return [(frontmatter(c), c) for c in cards]


def build() -> str:
    roles = routing_roles()
    L: list[str] = []
    L.append("<!-- GENERATED by scripts/build_methods_index.py — DO NOT EDIT.")
    L.append("     Every row is derived from a card's frontmatter joined with")
    L.append("     methods/shotgun-routing.yaml. Fix the card or the routing file, then rerun:")
    L.append("       python3 scripts/build_methods_index.py")
    L.append("-->")
    L.append("")
    L.append("# Methods Library Index")
    L.append("")
    L.append("**`methods/ideation/` is the ideation shotgun's method pool.** A card there is "
             "selectable; a card anywhere else is not, and its own `excluded_because:` says why.")
    L.append("")
    L.append("The failure mode that makes the boundary a folder rather than a convention: an agent "
             "handed a card it cannot run does not report that it cannot run it. It produces a "
             "fluent, well-formed, entirely invented result, indistinguishable from evidence at "
             "synthesis time.")
    L.append("")
    L.append("## Ideation Methods — the shotgun pool")
    L.append("")
    L.append("| Method | Category | Family | Role | File |")
    L.append("|---|---|---|---|---|")
    for fm, path in rows_for("ideation"):
        rel = f"ideation/{path.name}"
        fam, role = roles.get(f"methods/{rel}", ("—", "—"))
        L.append("| %s | %s | %s | %s | [%s](%s) |" % (
            fm.get("name", path.stem), fm.get("category", "—"), fam, role, path.name, rel))
    L.append("")

    for folder in ("validation", "mutation", "intake", "practices", "unused"):
        title, note = FOLDER_NOTES[folder]
        L.append("---")
        L.append("")
        L.append(f"## {title}")
        L.append("")
        L.append(note)
        L.append("")
        if folder == "intake":
            L.append("| Method | Elicits | Feeds | File |")
            L.append("|---|---|---|---|")
            for fm, path in rows_for(folder):
                L.append("| %s | %s | %s | [%s](%s/%s) |" % (
                    fm.get("name", path.stem), fm.get("elicits", "—"),
                    fm.get("feeds", "—"), path.name, folder, path.name))
        else:
            L.append("| Method | Category | Why it is not a shotgun lens | File |")
            L.append("|---|---|---|---|")
            for fm, path in rows_for(folder):
                reason = str(fm.get("excluded_because") or "—").replace("|", "\\|")
                L.append("| %s | %s | %s | [%s](%s/%s) |" % (
                    fm.get("name", path.stem), fm.get("category", "—"),
                    reason, path.name, folder, path.name))
        L.append("")

    history = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
    m = re.search(r"(?ms)^Deleted outright \(not parked\).*", history)
    if m:
        L.append("---")
        L.append("")
        L.append("## History — deleted cards and retired families")
        L.append("")
        L.append("_Hand-authored below this line; the generator preserves it verbatim._")
        L.append("")
        L.append(m.group(0).rstrip())
        L.append("")
    return "\n".join(L)


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current.strip() != content.strip():
            print("[stale] methods/index.md — run: python3 scripts/build_methods_index.py")
            return 1
        print("methods/index.md current.")
        return 0
    INDEX.write_text(content + "\n", encoding="utf-8")
    print(f"[ok] wrote {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
