#!/usr/bin/env python3
"""Fail the commit when a fact has drifted from its single author.

This repo's design rule is: one fact, one author; everything read first is generated
from those authors. That rule was already written down before this file existed, and
it was violated in five places simultaneously, silently, for weeks — because nothing
checked. A design that depends on people noticing is not a design.

Each check below exists because a specific thing actually broke:

  1. brief-fresh   BRIEF.md's recorded source hashes still match the sources.
                   (The artifact read first must never be older than what it summarises.)
  2. state-prose   No current-state assertion in prose under reports/.
                   (hunch-lineage.md claimed "H004 (active)" for a day after H004 was
                   folded into an offering, while its own frontmatter said H003.)
  3. vocab         Every governed enum value is declared in schemas/vocabularies.yaml.
                   ("evidence" had three incompatible vocabularies; hunch status had two
                   undeclared values in the live file.)
  4. skill-desc    No skill body says SUPERSEDED while its description advertises it as
                   live. (startup-generate-dashboard did exactly this; the description is
                   the only part read before the routing decision.)
  5. routing       Every skill named in CLAUDE.md's routing table exists.
                   (It routed architecture work to /brainstorming, which does not exist.)
  6. generated     No hand-edit of a generated file.

Usage:
    python3 scripts/validate_repo.py            # all checks
    python3 scripts/validate_repo.py --fix-hint # print the command that fixes each failure

Exit 0 clean, 1 on any violation.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
VOCAB_FILE = ROOT / "schemas" / "vocabularies.yaml"

sys.path.insert(0, str(ROOT))
from scripts.idea import DATED_PART  # noqa: E402 — dated vs living has one author

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip3 install -r requirements.txt")


# Fields whose values are governed by a vocabulary, and where they may appear.
# Only fields with a CLOSED value set belong here — a field that legitimately takes
# free text must not be listed, or the check becomes noise people learn to ignore.
GOVERNED = {
    "01-ideation/hunch-lineage.md": {
        "status": "hunch_status",
        "validation_status": "hunch_validation_status",
    },
    "02-assumptions/graph.md": {
        "status": "assumption_status",
        "category": "assumption_category",
        "lens": "lens",
        "validation_track": "validation_track",
        "quadrant": "quadrant",
        "importance": "importance",
    },
    "03-validation/evidence.md": {
        "verdict": "verdict",
        "source_type": "evidence_source_type",
    },
    "outreach/contacts.md": {
        "signal_type": "signal_type",
        "contact_role": "contact_role",
        "outcome_modifier": "outcome_modifier",
    },
}

LEDGERS = {
    "03-validation/evidence.md": re.compile(r"^  - id: (E\w+)\s*$", re.M),
    "02-assumptions/graph.md": re.compile(r"^  - id: ((?:H\d+)?A\w+)\s*$", re.M),
    "outreach/contacts.md": re.compile(r"^id: (C\w+)\s*$", re.M),
}

# Where an E-id is cited as a structured reference rather than mentioned in prose.
# Prose mentions are deliberately NOT checked: a dated snapshot may legitimately
# discuss an entry that has since been deleted.
CITE_BLOCK = re.compile(r"^    evidence_(?:for|against):\s*$")
CITE_END = re.compile(r"^(?:  - id:|    [a-z_]+:)")
OFFERING_CITE = re.compile(r"^\s*evidence:\s*\[([^\]]*)\]", re.M)


# Prose that asserts *current* state. State belongs in frontmatter or a `status:` field.
STATE_PROSE = re.compile(
    r"(?:^##+ .*—\s*(?:ACTIVE|RETIRED|KILLED|SUPERSEDED|FOLDED)\b"
    r"|\bis now \*\*[A-Z]\d+"
    r"|\bcurrently the active\b)",
    re.M,
)

GENERATED_MARKER = "GENERATED by scripts/"


def _vocab():
    # The registry is the root authority for every other check, so a malformed one is
    # fatal rather than a finding — but it must say so in one line, not a traceback.
    try:
        data = yaml.safe_load(VOCAB_FILE.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as e:
        sys.exit("FATAL: schemas/vocabularies.yaml does not parse — every other check "
                 "depends on it.\n%s" % e)
    out = {}
    for name, spec in (data.get("vocabularies") or {}).items():
        values = spec.get("values") if isinstance(spec, dict) else None
        if isinstance(values, dict):
            out[name] = {str(k) for k in values}
        elif isinstance(values, list):
            out[name] = {str(v) for v in values}
    return out


def _slugs():
    if not REPORTS.is_dir():
        return []
    return sorted(p.name for p in REPORTS.iterdir() if p.is_dir())


def _frontmatter_span(text: str):
    """Character range of the leading YAML frontmatter, or (0, 0)."""
    if not text.startswith("---"):
        return 0, 0
    end = text.find("\n---", 3)
    return (0, end + 4) if end != -1 else (0, 0)


# ─── checks ──────────────────────────────────────────────────────────────────


def check_brief_fresh(errors):
    sys.path.insert(0, str(ROOT))
    try:
        from scripts.build_brief import is_stale
    except Exception as e:
        errors.append(("brief-fresh", "cannot import build_brief: %s" % e, ""))
        return
    for slug in _slugs():
        if is_stale(slug):
            errors.append((
                "brief-fresh",
                "reports/%s/BRIEF.md is missing or stale against its sources" % slug,
                "python3 scripts/build_brief.py %s" % slug,
            ))


def check_state_prose(errors):
    for md in sorted(REPORTS.rglob("*.md")):
        if md.name == "BRIEF.md":
            continue
        text = md.read_text(encoding="utf-8", errors="replace")
        fm_start, fm_end = _frontmatter_span(text)
        for m in STATE_PROSE.finditer(text):
            if fm_start <= m.start() < fm_end:
                continue  # frontmatter is allowed to assert state — it owns it
            line = text.count("\n", 0, m.start()) + 1
            errors.append((
                "state-prose",
                "%s:%d asserts current state in prose: %r"
                % (md.relative_to(ROOT), line, m.group(0).strip()[:60]),
                "move it to a `status:` field; rewrite the prose as dated past-tense history",
            ))


def check_vocab(errors):
    vocab = _vocab()

    # Method cards live outside reports/ but are governed the same way — the category
    # set had drifted three ways (schema 14, extract-method skill 13, cards using two
    # values declared nowhere) before this check existed.
    allowed = vocab.get("method_category") or set()
    for card in sorted((ROOT / "methods").rglob("*.md")):
        if card.name == "index.md":
            continue
        text = card.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"^category:\s*([A-Za-z0-9_-]+)\s*$", text, re.M)
        if m and m.group(1) not in allowed:
            errors.append((
                "vocab",
                "%s:%d — category: %r not in vocab:method_category"
                % (card.relative_to(ROOT), text.count("\n", 0, m.start()) + 1, m.group(1)),
                "fix the value, or declare it in schemas/vocabularies.yaml with what it means",
            ))

    for slug in _slugs():
        for rel, fields in GOVERNED.items():
            path = REPORTS / slug / rel
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            for field, vname in fields.items():
                allowed = vocab.get(vname)
                if not allowed:
                    errors.append((
                        "vocab",
                        "vocabulary %r referenced by %s is not declared" % (vname, field),
                        "declare it in schemas/vocabularies.yaml",
                    ))
                    continue
                pattern = re.compile(r"^\s*%s:\s*([A-Za-z0-9_+\-]+)\s*$" % re.escape(field), re.M)
                for m in pattern.finditer(text):
                    value = m.group(1)
                    if value in allowed:
                        continue
                    line = text.count("\n", 0, m.start()) + 1
                    errors.append((
                        "vocab",
                        "%s:%d — %s: %r not in vocab:%s (%s)"
                        % (path.relative_to(ROOT), line, field, value, vname,
                           ", ".join(sorted(allowed))),
                        "fix the value, or declare it in schemas/vocabularies.yaml with what it means",
                    ))


def check_skill_descriptions(errors):
    for skill in sorted((ROOT / ".claude" / "skills").glob("*/SKILL.md")):
        text = skill.read_text(encoding="utf-8", errors="replace")
        fm_start, fm_end = _frontmatter_span(text)
        fm, body = text[fm_start:fm_end], text[fm_end:]
        if re.search(r"\bSUPERSEDED\b|\bDEPRECATED\b", body) and not re.search(
            r"\bsuperseded\b|\bdeprecated\b", fm, re.I
        ):
            errors.append((
                "skill-desc",
                "%s body says SUPERSEDED but its description does not"
                % skill.relative_to(ROOT),
                "say so in `description:` (it is the only part read before routing), or delete the skill",
            ))


def check_routing(errors):
    """Every skill named anywhere must exist.

    Covers CLAUDE.md's routing rows AND cross-references between skills. Deleting
    a superseded skill left two live skills still calling
    `Skill({ skill: "startup-generate-dashboard" })`, which would fail at run time
    with nothing to catch it — a dangling reference is invisible until a founder
    hits it mid-workflow.
    """
    known = {p.name for p in (ROOT / ".claude" / "skills").glob("*") if p.is_dir()}
    if not known:
        return

    targets = [(ROOT / "CLAUDE.md", r"`/([a-z][a-z0-9-]+)`", True)]
    for skill_md in sorted((ROOT / ".claude" / "skills").glob("*/SKILL.md")):
        targets.append((skill_md, r'Skill\(\{\s*skill:\s*"([a-z][a-z0-9-]+)"', False))

    for path, pattern, rows_only in targets:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(pattern, text):
            name = m.group(1)
            if name in known or not name.startswith("startup-"):
                continue
            if rows_only:
                # In CLAUDE.md only flag names presented as routing targets.
                line = text[text.rfind("\n", 0, m.start()) + 1:text.find("\n", m.start())]
                if "|" not in line:
                    continue
            line_no = text.count("\n", 0, m.start()) + 1
            errors.append((
                "routing",
                "%s:%d names skill %r, which has no definition in .claude/skills/"
                % (path.relative_to(ROOT), line_no, name),
                "point it at a real skill or a script, or drop the reference",
            ))


def check_generated_not_edited(errors):
    for path in sorted(REPORTS.rglob("BRIEF.md")):
        text = path.read_text(encoding="utf-8", errors="replace")
        if GENERATED_MARKER not in text:
            errors.append((
                "generated",
                "%s lost its GENERATED header — it was probably hand-written"
                % path.relative_to(ROOT),
                "python3 scripts/build_brief.py %s" % path.parent.name,
            ))


def check_no_restatement(errors):
    """Guard the merges: a fact whose author is elsewhere must not be re-authored.

    The rule below closed a live drift on 2026-08-07 and would silently reopen —
    tables are the easiest thing in the world to helpfully re-add. It checks a
    structural fact (does a routing row name a skill that has its own description?)
    rather than one file's formatting, which is why it survived the 2026-08-07
    review that removed its sibling.
    """
    # 1. CLAUDE.md must not restate what a skill's own description already says, and
    #    which the harness injects into every session for free.
    claude_md = ROOT / "CLAUDE.md"
    if claude_md.exists():
        skills = {p.name for p in (ROOT / ".claude" / "skills").glob("*") if p.is_dir()}
        for m in re.finditer(r"^\|.*?\|\s*`/([a-z0-9-]+)`", claude_md.read_text(
                encoding="utf-8", errors="replace"), re.M):
            if m.group(1) in skills:
                errors.append((
                    "no-restatement",
                    "CLAUDE.md has a routing row for `/%s`, whose description already "
                    "says when to use it" % m.group(1),
                    "delete the row; keep only rows whose answer is NOT a skill",
                ))

    # A second rule used to live here, scanning api-catalog.md for re-declared
    # reachability (Auth / Env vars / Endpoint bullets). Removed 2026-08-07: it
    # hardcoded one file's path AND its exact markdown formatting, so it was two
    # special cases wearing a rule's clothing — it would have broken silently the
    # first time that file was restructured, and its failure message was
    # unintelligible to anyone who had not written it. The rule itself still
    # holds; it is stated where it is enforceable by a reader, in that file's own
    # header. A convention a human can see beats a regex that guesses at layout.


def check_no_hand_derived(errors):
    """8. derived-fields — assumption-level evidence strength is computed, never authored.

    `evidence_quality:` and node-level `confidence:` were hand-set copies of
    what the ledger already implies; they drifted (consolidated 2026-08-09).
    The generators derive them from linked entries — a hand-set copy reappearing
    in a graph.md is the old three-ladder drift coming back.
    """
    for graph in ROOT.glob("reports/*/02-assumptions/graph.md"):
        text = graph.read_text(encoding="utf-8")
        for lineno, line in enumerate(text.splitlines(), 1):
            s = line.strip()
            if s.startswith("evidence_quality:") or (
                    line.startswith("    confidence:") and
                    s.split(":", 1)[1].strip() in ("low", "medium", "high")):
                errors.append((
                    "derived-fields",
                    "%s:%d hand-sets '%s' — assumption evidence strength is derived "
                    "from the ledger by the generators; delete the field"
                    % (graph.relative_to(ROOT), lineno, s.split(":")[0]),
                    "remove the line; scripts/idea.py derive_assumption_evidence() owns it",
                ))


def check_routing_resolves(errors):
    """9. routing-paths — every method named in shotgun-routing.yaml exists.

    methods/index.md used to warn that moving a card could silently orphan a
    routing family: the run still completes, the report still looks whole, and
    the missing lens is invisible. A warning is not a guard; this is.
    """
    routing = ROOT / "methods" / "shotgun-routing.yaml"
    if not routing.is_file():
        return
    try:
        data = yaml.safe_load(routing.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as e:
        errors.append(("routing-paths", "shotgun-routing.yaml does not parse: %s" % e, ""))
        return

    def check(path, where):
        if isinstance(path, str) and path.endswith(".md") and not (ROOT / path).is_file():
            errors.append((
                "routing-paths",
                "%s names %s, which does not exist" % (where, path),
                "restore the card, or update shotgun-routing.yaml and rerun "
                "scripts/build_methods_index.py",
            ))

    check((data.get("pre_lens") or {}).get("method"), "pre_lens")
    for name, fam in (data.get("lens_families") or {}).items():
        if not isinstance(fam, dict):
            continue
        check(fam.get("primary"), "lens_families.%s.primary" % name)
        for entry in fam.get("alternatives") or []:
            check(entry.get("method") if isinstance(entry, dict) else entry,
                  "lens_families.%s.alternatives" % name)


def check_doc_paths_exist(errors):
    """10. doc-paths — repo paths named in the always-on docs must exist.

    ARCHITECTURE.md and CLAUDE.md are read at session start, so a dead path in
    them is read as structure. Five had accumulated: an empty case database, two
    orphan schemas, an eval directory nobody ever created, and an `ideas/{slug}.md`
    artifact the intake skill does not write.
    """
    PATH_RE = re.compile(r"`([A-Za-z0-9_./-]+/[A-Za-z0-9_./-]*)`")
    for doc in ("ARCHITECTURE.md", "CLAUDE.md", "README.md"):
        path = ROOT / doc
        if not path.is_file():
            continue
        for raw in sorted(set(PATH_RE.findall(path.read_text(encoding="utf-8")))):
            if "{" in raw or "*" in raw or raw.startswith(("http", "~")):
                continue
            rel = raw.lstrip("/")
            # Only repo-root-relative paths are checkable. A path whose first
            # segment is not a real top-level entry is relative to something else
            # (an idea folder, a profile URL) and is skipped rather than guessed at.
            root_segment = rel.split("/", 1)[0]
            if not (ROOT / root_segment).exists():
                continue
            if rel.endswith("/"):
                target, kind = ROOT / rel.rstrip("/"), "directory"
            elif "." in rel.rsplit("/", 1)[-1]:
                target, kind = ROOT / rel, "file"
            else:
                continue
            if not target.exists():
                errors.append((
                    "doc-paths",
                    "%s names %s `%s`, which does not exist" % (doc, kind, raw),
                    "create it, or remove the reference — a dead path in an "
                    "always-on doc reads as structure",
                ))


def _blob(rev: str, rel: str):
    """A file at some revision, or None if git cannot answer."""
    import subprocess
    try:
        r = subprocess.run(["git", "show", "%s:%s" % (rev, rel)], cwd=str(ROOT),
                           capture_output=True, text=True, timeout=10)
    except Exception:
        return None
    return r.stdout if r.returncode == 0 else None


def _head_blob(rel: str):
    """The committed version of a file, or None if git cannot answer."""
    return _blob("HEAD", rel)


def _merging():
    """True mid-merge — .git/MERGE_HEAD exists only between merge and commit."""
    import subprocess
    try:
        r = subprocess.run(["git", "rev-parse", "--git-dir"], cwd=str(ROOT),
                           capture_output=True, text=True, timeout=10)
    except Exception:
        return False
    if r.returncode != 0:
        return False
    git_dir = Path(r.stdout.strip())
    if not git_dir.is_absolute():
        git_dir = ROOT / git_dir
    return (git_dir / "MERGE_HEAD").is_file()


def _entry_dates(text: str):
    """{E-id: date} for an evidence ledger — the identity anchor for an entry."""
    out = {}
    current = None
    for line in text.splitlines():
        m = re.match(r"^  - id: (E\w+)\s*$", line)
        if m:
            current = m.group(1)
            continue
        if current:
            d = re.match(r"^    date:\s*(\S+)", line)
            if d:
                out[current] = d.group(1)
                current = None
    return out


def _entry_identities(text: str):
    """{(date, source): E-id} — an entry's identity independent of the id it holds.

    Used mid-merge, where ids legitimately move but claims may not vanish.
    """
    out, current, date = {}, None, None
    for line in text.splitlines():
        m = re.match(r"^  - id: (E\w+)\s*$", line)
        if m:
            current, date = m.group(1), None
            continue
        if current and date is None:
            d = re.match(r"^    date:\s*(\S+)", line)
            if d:
                date = d.group(1)
                continue
        if current and date is not None:
            s = re.match(r"^    source:\s*(.+?)\s*$", line)
            if s:
                out[(date, s.group(1).strip('"\'')[:80])] = current
                current, date = None, None
    return out


def check_ledger_ids(errors):
    """Keep append-only ledgers well-shaped across parallel pushes.

    Three failures, all of which actually happened while two founders pushed in
    parallel and `main` moved underneath open work:

      duplicate   Both sides append from the same next-free id, then git merges at
                  the same offset. Cost: C98-C135 renumbered to C101-C138, three
                  contacts lost inside a 2100-line conflict, and two A-id collisions.
      dangling    An entry is deleted and the citations to it are not. E54-E61 went
                  and graph.md/offerings.md were never re-checked.
      reassigned  THE SILENT ONE, and the reason this check exists. E48 was reused
                  for a different claim on a different date. Every citation to it
                  still resolved, so nothing anywhere failed — the text just stopped
                  being true. A deleted id fails loudly; a reused one does not.
    """
    for slug in _slugs():
        # 1. no duplicate ids inside one ledger
        for rel, pattern in LEDGERS.items():
            path = REPORTS / slug / rel
            if not path.exists():
                continue
            ids = pattern.findall(path.read_text(encoding="utf-8", errors="replace"))
            seen, dupes = set(), []
            for i in ids:
                (dupes.append(i) if i in seen else seen.add(i))
            for i in sorted(set(dupes)):
                errors.append((
                    "ledger-ids",
                    "%s declares id %s more than once" % (path.relative_to(ROOT), i),
                    "two sessions allocated it against the same base; renumber the side "
                    "that has NOT reached main, and never reuse a retired id",
                ))

        # 2. structured citations resolve
        ev_path = REPORTS / slug / "03-validation/evidence.md"
        if not ev_path.exists():
            continue
        known = set(LEDGERS["03-validation/evidence.md"].findall(
            ev_path.read_text(encoding="utf-8", errors="replace")))

        cited = {}  # id -> "file:line"
        graph = REPORTS / slug / "02-assumptions/graph.md"
        if graph.exists():
            inside = False
            for n, line in enumerate(graph.read_text(
                    encoding="utf-8", errors="replace").splitlines(), 1):
                if CITE_BLOCK.match(line):
                    inside = True
                    continue
                if inside and CITE_END.match(line):
                    inside = False
                if inside:
                    for eid in re.findall(r"\bE\d+\b", line):
                        cited.setdefault(eid, "%s:%d" % (graph.relative_to(ROOT), n))

        offerings = REPORTS / slug / "04-mutation/offerings.md"
        if offerings.exists():
            text = offerings.read_text(encoding="utf-8", errors="replace")
            for m in OFFERING_CITE.finditer(text):
                n = text.count("\n", 0, m.start()) + 1
                for eid in re.findall(r"\bE\d+\b", m.group(1)):
                    cited.setdefault(eid, "%s:%d" % (offerings.relative_to(ROOT), n))

        for eid, where in sorted(cited.items()):
            if eid not in known:
                errors.append((
                    "ledger-ids",
                    "%s cites %s, which is not in %s"
                    % (where, eid, ev_path.relative_to(ROOT)),
                    "the entry was deleted or renumbered — re-point the citation at what "
                    "actually supports the claim, or drop it",
                ))

        # 3. a published id must not be reassigned to a different entry
        rel = "reports/%s/03-validation/evidence.md" % slug
        head = _head_blob(rel)
        if head is None:
            continue
        current = ev_path.read_text(encoding="utf-8", errors="replace")

        # Mid-merge the id->date test is the WRONG test, because rule 2 ("main wins
        # every ID contest") requires the losing side to renumber — which changes the
        # date at an id by design. Checking stability there would fail every correctly
        # resolved merge, and a gate that fires on the prescribed resolution just
        # teaches people to bypass it. What still must hold is CONSERVATION: every
        # entry either parent had must survive somewhere under some id. That is what
        # actually catches the E48 failure (a claim silently replaced) and it also
        # catches the merge-specific one (a claim dropped inside a text conflict).
        if _merging():
            other = _blob("MERGE_HEAD", rel)
            here = _entry_identities(current)
            for side, blob in (("HEAD", head), ("MERGE_HEAD", other)):
                if blob is None:
                    continue
                for ident, eid in sorted(_entry_identities(blob).items()):
                    if ident not in here:
                        errors.append((
                            "ledger-ids",
                            "merge drops the %s entry %s (%s — %s)"
                            % (side, eid, ident[0], ident[1][:60]),
                            "merge ledgers at ENTRY granularity, not as text: every entry "
                            "from both parents must survive, renumbered if main won its id",
                        ))
            continue

        was, now = _entry_dates(head), _entry_dates(current)
        for eid, old in sorted(was.items()):
            new = now.get(eid)
            if new and new != old:
                errors.append((
                    "ledger-ids",
                    "%s changed date %s -> %s: an id already committed is being reused "
                    "for a different entry" % (eid, old, new),
                    "give the new entry the next free id and leave %s burned; if this is "
                    "a genuine date correction, confirm nothing still cites %s for the "
                    "old claim" % (eid, eid),
                ))


def check_lifecycle_slugs(errors):
    """12. lifecycle-slugs — every slug in lifecycle.yaml has a reports/ folder.

    lifecycle.yaml is the one authored index of which ideas exist. When an idea's
    folder is deleted and its entry is not, the generators iterate a slug with no
    data and the index quietly describes something that is gone.
    """
    lifecycle = ROOT / "reports" / "lifecycle.yaml"
    if not lifecycle.is_file():
        return
    try:
        data = yaml.safe_load(lifecycle.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as e:
        errors.append(("lifecycle-slugs", "lifecycle.yaml does not parse: %s" % e, ""))
        return
    for slug in (data.get("ideas") or {}):
        if not (ROOT / "reports" / slug).is_dir():
            errors.append((
                "lifecycle-slugs",
                "lifecycle.yaml lists '%s' but reports/%s/ does not exist" % (slug, slug),
                "drop the entry, or restore the folder — the index and the tree must agree",
            ))


def check_purpose_declared(errors):
    """13. purpose — every living artifact opens with `purpose:`.

    The brief's inventory is generated from these lines, and it is the thing that
    answers "does something already cover this?" before a session writes a second
    author for an existing fact. Without a `purpose:`, the generator falls back to
    the file's title, which restates the filename and prevents nothing — six of
    eleven living artifacts were in that state, so the inventory that exists to stop
    duplicate artifacts was running at about half strength.

    Living = not dated and not generated. A dated artifact is an immutable snapshot;
    its filename already says what it is.
    """
    generated = re.compile(r"^(BRIEF|results-.*)\.md$")
    for slug_dir in sorted(p for p in REPORTS.glob("*") if p.is_dir()):
        for path in sorted(slug_dir.rglob("*.md")):
            rel = path.relative_to(ROOT)
            if DATED_PART.search(str(rel)) or generated.match(path.name):
                continue
            head = path.read_text(encoding="utf-8", errors="replace")[:4000]
            if not re.search(r"^purpose:", head, re.M):
                errors.append((
                    "purpose",
                    "%s is a living artifact with no `purpose:` line" % rel,
                    "add `purpose: <the one fact this file owns>` to its frontmatter — "
                    "the brief's inventory is generated from it",
                ))


def check_status_vs_evidence(errors):
    """14. status-evidence — an assumption cannot be `untested` once evidence links to it.

    `schemas/vocabularies.yaml` defines assumption_status.untested as "No evidence
    gathered." On 2026-09-03 H3A1-H3A3 all read `untested` while six ledger entries
    pointed straight at them, including three CONTRADICTING H3A3 — so the graph said
    nothing had been learned while the ledger said the willingness-to-pay node was in
    trouble. Status is a founder decision and is never auto-flipped; this check just
    refuses to let the two drift silently.
    """
    for graph in ROOT.glob("reports/*/02-assumptions/graph.md"):
        slug = graph.parents[1].name
        ledger = ROOT / "reports" / slug / "03-validation" / "evidence.md"
        if not ledger.exists():
            continue
        linked = {}
        for line in ledger.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if s.startswith("assumption_linked:"):
                aid = s.split(":", 1)[1].strip()
                if aid and aid != "unassigned":
                    linked[aid] = linked.get(aid, 0) + 1
        aid = None
        for lineno, line in enumerate(graph.read_text(encoding="utf-8").splitlines(), 1):
            s = line.strip()
            if s.startswith("- id:"):
                aid = s.split(":", 1)[1].strip()
            elif s.startswith("status:") and aid:
                if s.split(":", 1)[1].strip() == "untested" and linked.get(aid):
                    errors.append((
                        "status-evidence",
                        "%s:%d %s is `untested` but %d ledger entr%s to it"
                        % (graph.relative_to(ROOT), lineno, aid, linked[aid],
                           "y links" if linked[aid] == 1 else "ies link"),
                        "set status per schemas/vocabularies.yaml assumption_status "
                        "(weakly_supported / contested / confirmed / killed) — a founder "
                        "call, not an automatic one",
                    ))
                aid = None


CHECKS = [
    ("brief-fresh", check_brief_fresh),
    ("state-prose", check_state_prose),
    ("vocab", check_vocab),
    ("skill-desc", check_skill_descriptions),
    ("routing", check_routing),
    ("generated", check_generated_not_edited),
    ("no-restatement", check_no_restatement),
    ("ledger-ids", check_ledger_ids),
    ("derived-fields", check_no_hand_derived),
    ("routing-paths", check_routing_resolves),
    ("doc-paths", check_doc_paths_exist),
    ("lifecycle-slugs", check_lifecycle_slugs),
    ("purpose", check_purpose_declared),
    ("status-evidence", check_status_vs_evidence),
]


def main() -> int:
    show_hint = "--fix-hint" in sys.argv
    errors = []
    for _name, fn in CHECKS:
        fn(errors)

    if not errors:
        print("Repo valid: %d checks, %d ideas." % (len(CHECKS), len(_slugs())))
        return 0

    by_check = {}
    for name, msg, hint in errors:
        by_check.setdefault(name, []).append((msg, hint))

    print("Repo validation failed (%d issue(s)):\n" % len(errors))
    for name, items in by_check.items():
        print("[%s]" % name)
        for msg, hint in items:
            print("  - %s" % msg)
            if show_hint and hint:
                print("    → %s" % hint)
        print("")
    if not show_hint:
        print("Rerun with --fix-hint for the fix for each.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
